from .cpu import CPU
from .enums import (
    CmakeBuildType,
    CompilerKind,
    CudaPythonVariant,
    DiskKind,
    Scheduler,
    SystemFamily,
    ToolCategory,
    UnitKind,
    Vendor,
)
from .gpu import GPU
from .host import Host
from .machine import Machine
from .models import (
    Board,
    Clock,
    ClockInfo,
    CompilerInfo,
    ComputeCapability,
    CpuSnapshot,
    CudaPythonInfo,
    DetectedTool,
    DriveInfo,
    EnergyReading,
    Environment,
    GPUSnapshot,
    HostDisk,
    MachineSnapshot,
    Memory,
    MemoryCard,
    MemoryHardware,
    Meter,
    PartitionInfo,
    PcieInfo,
    ProcessInfo,
    SystemCompilers,
    ThermalState,
    ThermalTracker,
    ThrottleReason,
    Toolchain,
    ToolProbe,
    UnitSnapshot,
    Utilization,
    meter,
)
from .npu import NPU
from .profiling import (
    Bound,
    KernelStat,
    ProfileReport,
    gpu_busy,
    wait_for_idle,
)
from .profiling import profile_fn as profile
from .providers import (
    AMDGPU,
    AppleGPU,
    AppleNPU,
    IntelGPU,
    IntelNPU,
    NvidiaGPU,
    QualcommGPU,
    QualcommNPU,
)
from .unit import Unit
from .visual import MachineView

NAME = __name__  # the package folder is the single source of the name

__all__ = [
    "NAME",
    "CPU",
    "GPU",
    "NPU",
    "AMDGPU",
    "AppleGPU",
    "AppleNPU",
    "Board",
    "Bound",
    "Clock",
    "ClockInfo",
    "CmakeBuildType",
    "CompilerInfo",
    "CompilerKind",
    "ComputeCapability",
    "CpuSnapshot",
    "CudaPythonInfo",
    "CudaPythonVariant",
    "DetectedTool",
    "DiskKind",
    "DriveInfo",
    "EnergyReading",
    "Environment",
    "GPUSnapshot",
    "Host",
    "HostDisk",
    "IntelGPU",
    "IntelNPU",
    "KernelStat",
    "Machine",
    "MachineSnapshot",
    "MachineView",
    "Memory",
    "MemoryCard",
    "MemoryHardware",
    "Meter",
    "NvidiaGPU",
    "PartitionInfo",
    "ProfileReport",
    "PcieInfo",
    "ProcessInfo",
    "QualcommGPU",
    "QualcommNPU",
    "Scheduler",
    "SystemCompilers",
    "SystemFamily",
    "ThermalState",
    "ThermalTracker",
    "ThrottleReason",
    "ToolCategory",
    "ToolProbe",
    "Toolchain",
    "Unit",
    "UnitKind",
    "UnitSnapshot",
    "Utilization",
    "Vendor",
    "gpu_busy",
    "meter",
    "profile",
    "wait_for_idle",
]
