from __future__ import annotations

from .cpu import CPU
from .enums import (
    CmakeBuildType,
    CompilerKind,
    CudaPythonVariant,
    DiskKind,
    Scheduler,
    SystemFamily,
    UnitKind,
    Vendor,
)
from .gpu import GPU
from .host import Host
from .machine import Machine
from .models import (
    Board,
    Clock,
    ClockInfo,
    CompilerInfo,
    ComputeCapability,
    CpuSnapshot,
    CudaPythonInfo,
    DriveInfo,
    EnergyInterval,
    EnergyReading,
    Environment,
    GPUSnapshot,
    HostDisk,
    HostMemory,
    MachineSnapshot,
    MemInfo,
    MemoryCard,
    MemoryUsage,
    PartitionInfo,
    PcieInfo,
    ProcessInfo,
    SystemCompilers,
    ThermalState,
    ThermalTracker,
    ThrottleReason,
    UnitSnapshot,
    Utilization,
)
from .npu import NPU
from .providers import (
    AMDGPU,
    AppleGPU,
    AppleNPU,
    IntelGPU,
    IntelNPU,
    NvidiaGPU,
    QualcommGPU,
    QualcommNPU,
)
from .unit import Unit
from .visual import MachineView

NAME = __name__  # the package folder is the single source of the name

__all__ = [
    "NAME",
    "CPU",
    "GPU",
    "NPU",
    "AMDGPU",
    "AppleGPU",
    "AppleNPU",
    "Board",
    "Clock",
    "ClockInfo",
    "CmakeBuildType",
    "CompilerInfo",
    "CompilerKind",
    "ComputeCapability",
    "CpuSnapshot",
    "CudaPythonInfo",
    "CudaPythonVariant",
    "DiskKind",
    "DriveInfo",
    "EnergyInterval",
    "EnergyReading",
    "Environment",
    "GPUSnapshot",
    "Host",
    "HostDisk",
    "HostMemory",
    "IntelGPU",
    "IntelNPU",
    "Machine",
    "MachineSnapshot",
    "MachineView",
    "MemInfo",
    "MemoryCard",
    "MemoryUsage",
    "NvidiaGPU",
    "PartitionInfo",
    "PcieInfo",
    "ProcessInfo",
    "QualcommGPU",
    "QualcommNPU",
    "Scheduler",
    "SystemCompilers",
    "SystemFamily",
    "ThermalState",
    "ThermalTracker",
    "ThrottleReason",
    "Unit",
    "UnitKind",
    "UnitSnapshot",
    "Utilization",
    "Vendor",
]
